<?php
/**
 * OMG Tech Hub — Portfolio Projects Data
 * Include this file in both portfolio.php and index.php
 */

$omgProjects = [

  // ── GRAPHIC DESIGN (1–8) ──────────────────────────────────────────────────
  [
    'id'=>1,'cat'=>'graphic','cat_label'=>'Graphic Design',
    'bg'=>'linear-gradient(145deg,#0a2a3a 0%,#1a6080 50%,#c8a050 100%)',
    'image'=>'images/gra1.jpeg',
    'url'=>'',
    'title'=>'Kings Travels — Maldives Luxury Flyer',
    'tagline'=>'Premium travel flyer for a high-end Maldives honeymoon package.',
    'brief'=>'Kings Travels needed a flyer for their ₦7,800,000 per-person Maldives package running 20th–25th June 2026, highlighting the unique waterfall resort architecture and a comprehensive package including Qatar Airways flights, overwater villa, private pool, sea-plane transfers, and romantic tours.',
    'problem'=>'Standard island travel flyers felt generic and failed to justify premium price points. This design needed to immediately communicate exclusivity and romance to convince high-spending couples that the package was worth every naira.',
    'process'=>'We led with the dramatic waterfall resort photography as the hero, using a textured overlay on the "Maldives" headline to mirror the natural resort aesthetic. A torn-paper divider cleanly separated the scenic image from the package details below.',
    'solution'=>'A visually immersive travel flyer featuring layered typography on the resort photography, circular preview images of the resort highlights, a clean two-column package layout, and a prominent price badge — all branded with the Kings Travels identity.',
    'output'=>'Print-ready flyer (JPEG), social media optimised version, and WhatsApp-shareable format.',
  ],
  [
    'id'=>2,'cat'=>'graphic','cat_label'=>'Graphic Design',
    'bg'=>'linear-gradient(145deg,#8B0000 0%,#CC0000 50%,#FF4444 100%)',
    'image'=>'images/gra2.jpeg',
    'url'=>'',
    'title'=>'OMG Graphics — Valentine Special Promo Flyer',
    'tagline'=>'Bold promotional flyer announcing a 30% Valentine discount on design services.',
    'brief'=>'OMG Graphics needed a Valentine\'s Day promotional flyer to announce a 30% discount across all their services — flyer design, logo design, sticker design, and banner design — to drive new client orders during the holiday season.',
    'problem'=>'The Valentine period is competitive for creative businesses. OMG Graphics needed a flyer that stood out in crowded social media feeds and motivated potential clients to act on the discount immediately.',
    'process'=>'We used a bold red gradient with floating 3D heart elements to create an instantly festive, high-energy feel. The OMG Graphics logo was centred prominently to build brand recognition while the service list and discount percentage were given maximum visual weight.',
    'solution'=>'A vibrant Valentine flyer with a warm red gradient background, 3D heart accents, bold script headline, a clean service listing in split panels, and a gold "30% Discount" call-out — complete with WhatsApp number and website address.',
    'output'=>'Social media optimised flyer (JPEG), WhatsApp-shareable version.',
  ],
  [
    'id'=>3,'cat'=>'graphic','cat_label'=>'Graphic Design',
    'bg'=>'linear-gradient(145deg,#1a0a00 0%,#8B4000 50%,#FFD700 100%)',
    'image'=>'images/gra3.jpeg',
    'url'=>'',
    'title'=>'David — Birthday Celebration Flyer',
    'tagline'=>'Multi-photo birthday flyer with dramatic composite design for a 20th April celebration.',
    'brief'=>'A client needed a premium birthday flyer for David celebrating on 20th April, incorporating multiple outfit photos from a dedicated photoshoot into a single visually impressive design.',
    'problem'=>'Single-photo birthday flyers had become ordinary. The client wanted something that felt like a magazine spread — showing David\'s full personality through multiple poses while maintaining a cohesive, celebratory design.',
    'process'=>'We built a composite layout using six supporting pose images arranged symmetrically around a large central portrait, with a honeycomb texture background adding depth and a golden ambient glow creating a warm, celebratory atmosphere.',
    'solution'=>'A dramatic birthday composite featuring a large hero portrait, six bordered supporting photos in a balanced grid layout, bold red script "Happy Birthday" lettering, the name "David" in heavy display type with a reflection effect, and the date badge.',
    'output'=>'Print-ready celebration flyer (JPEG) and social media shareable version.',
  ],
  [
    'id'=>4,'cat'=>'graphic','cat_label'=>'Graphic Design',
    'bg'=>'linear-gradient(145deg,#0a0a0a 0%,#1a1a1a 40%,#c87800 100%)',
    'image'=>'images/gra4.jpeg',
    'url'=>'',
    'title'=>'Rifkatu Ali Esq. — Call to Bar Ceremony Invitation',
    'tagline'=>'Formal invitation flyer for a barrister\'s Call to Bar ceremony in Abuja.',
    'brief'=>'A family needed a formal, prestigious invitation flyer for Rifkatu Ali Esq.\'s Call to Bar ceremony — marking her qualification as a Barrister and Solicitor of the Supreme Court with an LLB and BL (Second Class Upper) — taking place on Thursday 10th July 2025 at the Body of Benchers Complex, Abuja.',
    'problem'=>'A Call to Bar ceremony is one of the most significant milestones in a lawyer\'s career. The invitation needed to communicate the prestige and formality of the occasion while still feeling warm and celebratory for family and friends.',
    'process'=>'We used a dark, spotlight-lit background to convey gravitas and formality, with a gold and orange colour palette referencing legal tradition. The two portrait photos were placed prominently to personalise the invitation, with all event details clearly structured below.',
    'solution'=>'A formal event invitation with a dramatic dark background, warm spotlight effect, bold headline typography for "Call to Bar Ceremony," prominent dual portrait photos in legal attire, full event details including venue and time, and the OMG Graphics branding.',
    'output'=>'Print-ready invitation flyer (JPEG) and digital sharing version.',
  ],
  [
    'id'=>5,'cat'=>'graphic','cat_label'=>'Graphic Design',
    'bg'=>'linear-gradient(145deg,#1a0a30 0%,#6a3090 50%,#c8a050 100%)',
    'image'=>'images/gra5.jpeg',
    'url'=>'',
    'title'=>'Kings Travels — Qatar Trip Flyer',
    'tagline'=>'Striking travel flyer for a 5-day Qatar package at ₦2,600,000 per person.',
    'brief'=>'Kings Travels needed a promotional flyer for their 5-day Qatar trip running 20th–25th May 2026, featuring the iconic Katara Towers at sunset and a package including Qatar e-Visa, direct Qatar Airways flights, VIP hotel with daily breakfast, and return airport transfers.',
    'problem'=>'Qatar as a travel destination is less instinctively aspirational than beach destinations. The flyer needed to make Qatar\'s world-class architecture and luxury feel immediately exciting and desirable to a Nigerian audience.',
    'process'=>'We led with the iconic crescent-shaped Katara Towers at dusk as the hero image — one of Qatar\'s most recognisable architectural landmarks. The word "QATAR" was set in massive white display type overlaid on the image for immediate impact, with three circular preview images showing additional city highlights.',
    'solution'=>'A bold travel flyer with the dramatic Katara Towers sunset as the full-bleed hero, giant destination typography, a torn-paper texture divider, circular highlight images, a clean package list, and a prominent price badge — consistent with the Kings Travels brand.',
    'output'=>'Print-ready flyer (JPEG), social media version, and WhatsApp-shareable format.',
  ],
  [
    'id'=>6,'cat'=>'graphic','cat_label'=>'Graphic Design',
    'bg'=>'linear-gradient(145deg,#e8f4e8 0%,#4a7a4a 50%,#1a3a1a 100%)',
    'image'=>'images/gra6.jpeg',
    'url'=>'',
    'title'=>'SkyRise Realty — New Week Social Media Post',
    'tagline'=>'Weekly motivational social media post for a real estate investment company.',
    'brief'=>'SkyRise Realty Ltd needed a branded social media post to kick off the week — combining a "Happy New Week" greeting with a visual reminder of their three core offerings: land, property, and investment — with their contact details and social media handles.',
    'problem'=>'Real estate companies often produce generic, text-heavy social media content that fails to engage audiences. SkyRise needed a post that felt fresh and motivational while clearly communicating what the business does.',
    'process'=>'We used a bright outdoor property image as the background to set an aspirational tone, placing a bold directional signpost graphic showing "Land," "Property," and "Investment" as the visual anchor — instantly communicating the business offering without reading a single word of copy.',
    'solution'=>'A clean, bright social post featuring a script "Happy New Week" headline, a three-direction signpost graphic for the core services, motivational subtext, and the SkyRise Realty logo and full contact footer with address, social media handles, and phone numbers.',
    'output'=>'Social media optimised post (JPEG) for Instagram, Facebook, and WhatsApp.',
  ],
  [
    'id'=>7,'cat'=>'graphic','cat_label'=>'Graphic Design',
    'bg'=>'linear-gradient(145deg,#001a60 0%,#0033cc 50%,#004400 100%)',
    'image'=>'images/gra7.jpeg',
    'url'=>'',
    'title'=>'Femo Homes & Gardens — Property Listing Flyer',
    'tagline'=>'Eye-catching property listing flyer for a 4-bedroom duplex in Lekki at ₦24 Million.',
    'brief'=>'Femo Homes and Gardens needed a promotional flyer for their newly built 4-bedroom semi-detached duplex house in Lekki, Ajah, Lagos — priced at ₦24 Million and featuring artistic architectural design, a boys\' quarter, and registered documents.',
    'problem'=>'Property listing flyers in Nigeria often look identical, making it hard for any single listing to stand out. Femo needed a design that made their property look premium and generated urgent interest from serious buyers.',
    'process'=>'We used the dramatic exterior architecture shot as the hero, with a strong blue brand panel below featuring hexagonal interior photo cutouts — a contemporary design treatment that elevated the listing above typical estate agency flyers.',
    'solution'=>'A bold two-section property flyer with a full-width exterior hero photo, a strong blue lower section with octagonal interior preview images, a "New Home Alert" headline, a feature description box, location details, and a prominent ₦24M price tag.',
    'output'=>'Print-ready property flyer (JPEG) and digital listing version.',
  ],
  [
    'id'=>8,'cat'=>'graphic','cat_label'=>'Graphic Design',
    'bg'=>'linear-gradient(145deg,#5a0a0a 0%,#8B1a1a 50%,#c8a050 100%)',
    'image'=>'images/gra8.jpeg',
    'url'=>'',
    'title'=>'Nerrg\'s Boutique — Fashion & Accessories Sales Flyer',
    'tagline'=>'Luxury fashion boutique sales flyer showcasing premium clothing and accessories.',
    'brief'=>'Nerrg\'s Boutique needed a promotional sales flyer to showcase their full range — trendy wears, designer bags, wrist watches, fashion heels, accessories, and perfumes — for their store at No 27 Ignhuonn Street, with social media handles for Instagram, Facebook, and TikTok.',
    'problem'=>'A fashion boutique selling across multiple product categories needed a flyer that communicated variety and luxury simultaneously — without feeling cluttered or losing the premium feel that justifies their pricing.',
    'process'=>'We used a deep red and gold colour scheme to instantly communicate luxury and boldness. The product photography was organised into a grid of six category thumbnails on the left, while three large mannequin displays dominated the right — creating a visual balance between breadth and premium quality.',
    'solution'=>'A rich, luxurious sales flyer featuring the boutique name and tagline in gold on deep red, a six-product category grid, three prominent fashion mannequin displays showing formal wear, a full product category list, store address, and all social media handles.',
    'output'=>'Print-ready sales flyer (JPEG), social media version for Instagram and Facebook, and WhatsApp-shareable format.',
  ],

  // ── WEB DEVELOPMENT (9–12) ────────────────────────────────────────────────
  [
    'id'=>9,'cat'=>'web','cat_label'=>'Web Development',
    'bg'=>'linear-gradient(145deg,#040810 0%,#0A66FF 60%,#7c3aed 100%)',
    'image'=>'images/webp1.png',
    'url'=>'https://miracleedetokon.kesug.com',
    'title'=>'Miracle Edet Okon — Personal Brand Website',
    'tagline'=>'Complete web presence build for a multi-disciplinary creative educator and brand designer.',
    'brief'=>'Miracle Edet Okon needed a complete personal brand website integrating her graphic design portfolio, a blog for her writing, a product store, an academy registration system, and a contact channel for clients and collaborators — all under one cohesive digital presence.',
    'problem'=>'Miracle had no website and was relying entirely on Instagram to showcase her work and connect with clients. This limited her ability to present a professional image, share long-form content, sell products directly, and reach audiences beyond social media.',
    'process'=>'We worked closely with Miracle to map her core user journeys — a potential client discovering her portfolio, a follower buying a product, and a student registering for her academy. The site architecture was planned to serve all three without creating confusion.',
    'solution'=>'A custom-built personal brand website featuring a dynamic design portfolio, an integrated blog, e-commerce functionality for digital product sales, an academy registration system, and a WhatsApp-based contact flow for fast client conversion.',
    'output'=>'Live website, source code, CMS access, and handover documentation.',
  ],
  [
    'id'=>10,'cat'=>'web','cat_label'=>'Web Development',
    'bg'=>'linear-gradient(145deg,#0f0f0f 0%,#1a1a1a 50%,#7A0D0D 100%)',
    'image'=>'images/webp2.png',
    'url'=>'https://omggraphics.great-site.net',
    'title'=>'OMG Graphics — Designer Portfolio Website',
    'tagline'=>'Conversion-focused portfolio website built to turn visitors into paying clients.',
    'brief'=>'OMG Graphics needed a portfolio website to professionally showcase his design work when applying for jobs and approaching potential clients — with a clear conversion path that moved visitors directly to placing an order via WhatsApp rather than slower email channels.',
    'problem'=>'Without a dedicated portfolio site, OMG Graphics had no professional digital presence to present to prospective clients or employers. Sharing work via social media links felt informal and made it difficult to control how his brand was perceived.',
    'process'=>'We designed the site around a single core goal: convert a portfolio visitor into a WhatsApp conversation as efficiently as possible. Every section — from the hero to the project showcases — was built with that conversion path in mind.',
    'solution'=>'A sleek, fast-loading portfolio website with a curated work showcase, a services section, client testimonials, and prominent WhatsApp CTAs throughout — removing email friction entirely and connecting potential clients to OMG Graphics instantly.',
    'output'=>'Live website, source code, and handover documentation.',
  ],
  [
    'id'=>11,'cat'=>'web','cat_label'=>'Web Development',
    'bg'=>'linear-gradient(145deg,#7A0D0D 0%,#F5B301 60%,#111 100%)',
    'image'=>'images/webp3.png',
    'url'=>'https://omgtechhub.great-site.net',
    'title'=>'OMG Tech Hub — Premium Creative Agency Website',
    'tagline'=>'Full business website for a premium creative-tech agency serving clients across Nigeria.',
    'brief'=>'OMG Tech Hub needed a world-class business website to represent the agency online — showcasing services across brand identity, graphic design, UI/UX, web development, motion graphics, and video — with a portfolio, blog, pricing, and a contact system built to convert serious clients.',
    'problem'=>'The agency had no dedicated web presence to validate its premium positioning. Without a site, potential clients had no way to understand the full scope of services, see past work, or trust that OMG Tech Hub was a credible, professional creative partner.',
    'process'=>'We built the site from the ground up using PHP, MySQL, and vanilla CSS/JS — designing every section to communicate premium quality. The architecture was planned to support long-term growth with a full blog CMS, admin panel, and AI chat widget.',
    'solution'=>'A feature-rich agency website with a glitch-effect hero, animated portfolio grid, service pages, tiered pricing in NGN, a blog with full admin management, an AI-powered chat widget, WhatsApp float, and dark/light mode — all optimised for performance.',
    'output'=>'Live website, full source code, admin panel, blog CMS, and complete handover documentation.',
  ],
  [
    'id'=>12,'cat'=>'web','cat_label'=>'Web Development',
    'bg'=>'linear-gradient(145deg,#0a0a1a 0%,#1a1060 50%,#4a2080 100%)',
    'image'=>'images/webp4.png',
    'url'=>'https://rhemasounds.great-site.net',
    'title'=>'Rhema Sounds — Church Music Streaming Platform',
    'tagline'=>'Custom streaming platform for ICCF Missions to share their songs and messages online.',
    'brief'=>'ICCF Missions needed a dedicated digital platform — Rhema Sounds — to stream their music and sermon messages to their congregation and the wider public, creating an accessible online home for their audio content.',
    'problem'=>'Without a dedicated platform, ICCF Missions had no centralised place for their community to access their music and messages online. Content was scattered and hard to find, limiting their reach and making it difficult to build a consistent listening audience.',
    'process'=>'We designed the platform around two primary content types — songs and messages — building a simple, intuitive listening experience that would work well for both young digital natives and older congregation members less familiar with streaming platforms.',
    'solution'=>'A clean, easy-to-navigate streaming website with separate sections for music and messages, an audio player, categorised content browsing, and a design that reflects the spiritual identity of ICCF Missions.',
    'output'=>'Live streaming platform, source code, content management access, and handover documentation.',
  ],

  // ── UI/UX DESIGN (13–20) ──────────────────────────────────────────────────
  [
    'id'=>13,'cat'=>'uiux','cat_label'=>'UI/UX Design',
    'bg'=>'linear-gradient(145deg,#070B12 0%,#00E5A0 100%)',
    'image'=>'images/ui1.png',
    'url'=>'',
    'title'=>'Zova — Fintech Super App',
    'tagline'=>'End-to-end UI/UX design for a next-generation financial super app.',
    'brief'=>'Zova needed a complete UI/UX design for their fintech super app — covering account dashboard, money transfers, card management, investments, and transaction history — for users across 12 African countries.',
    'problem'=>'Existing fintech apps in the market felt fragmented and clinical. Zova wanted a single intelligent platform that felt premium, fast, and human — without sacrificing the trust signals users need when dealing with money.',
    'process'=>'We conducted user research across Lagos, Nairobi, and Accra. Core user journeys were mapped — send money, receive, pay bills, and invest — and each flow was prototyped and tested with real users before visual design began.',
    'solution'=>'A dark-mode-first fintech app UI featuring a personalised balance dashboard, one-tap transfer flow, virtual card management, investment portfolio view, and real-time transaction feed. The green accent system communicates trust and growth throughout.',
    'output'=>'High-fidelity Figma prototype, full design system, component library, iOS & Android design files, and developer handoff documentation.',
  ],
  [
    'id'=>14,'cat'=>'uiux','cat_label'=>'UI/UX Design',
    'bg'=>'linear-gradient(145deg,#F5F0E8 0%,#2D9E6B 100%)',
    'image'=>'images/ui2.png',
    'url'=>'',
    'title'=>'Lumio — Health & Wellness App',
    'tagline'=>'Science-backed wellness app UI/UX with habit tracking and daily coaching.',
    'brief'=>'Lumio needed a complete UI/UX design for their health and wellness mobile app — daily wellness scoring, habit tracking, sleep analysis, mood logging, and personalised coaching — targeting health-conscious professionals.',
    'problem'=>'Most wellness apps felt either overly clinical or superficially motivational. Lumio needed a design that felt warm, personal, and trustworthy — one that would build a daily habit without feeling like another chore.',
    'process'=>'In-depth interviews with 22 wellness app users revealed that accountability and personalisation were the primary drivers of long-term retention. The UX was built around a daily "wellness score" that made progress visible and motivating.',
    'solution'=>'A warm light-mode wellness app with a personalised daily dashboard, animated wellness score ring, habit completion tracker, mood logging chips, and a streak system — all anchored in a calm green and cream visual language.',
    'output'=>'iOS and Android Figma design files, design system, interactive prototype, usability test report, and developer handoff package.',
  ],
  [
    'id'=>15,'cat'=>'uiux','cat_label'=>'UI/UX Design',
    'bg'=>'linear-gradient(145deg,#0C0C0A 0%,#C8A96E 100%)',
    'image'=>'images/ui3.png',
    'url'=>'',
    'title'=>'Nestara — Luxury Real Estate Platform',
    'tagline'=>'Premium property discovery platform UI/UX for Nigeria\'s high-net-worth market.',
    'brief'=>'Nestara needed a full UI/UX design for their luxury real estate platform — property search and filtering, immersive listing pages, virtual tour integration, agent profiles, and a mortgage calculator — positioned at Nigeria\'s premium property market.',
    'problem'=>'Luxury real estate in Nigeria had no digital platform that matched the quality expectations of high-net-worth buyers. Existing platforms felt generic, slow, and untrustworthy — undermining confidence in multi-hundred-million naira transactions.',
    'process'=>'We interviewed 14 high-net-worth property buyers and 8 estate agents. The research revealed that trust signals, beautiful imagery, and frictionless agent contact were the three most critical UX requirements.',
    'solution'=>'A dark-luxury editorial web platform with a sophisticated search experience, full-bleed property photography, detailed listing pages with virtual tour integration, verified agent profiles, and a seamless enquiry flow. Gold accents throughout communicate premium positioning.',
    'output'=>'Full desktop and mobile Figma design files, design system, interactive prototype, and developer handoff documentation.',
  ],
  [
    'id'=>16,'cat'=>'uiux','cat_label'=>'UI/UX Design',
    'bg'=>'linear-gradient(145deg,#FF4D1C 0%,#FF8A1C 100%)',
    'image'=>'images/ui4.png',
    'url'=>'',
    'title'=>'Cravio — Food Delivery App',
    'tagline'=>'Bold, high-energy food delivery app UI/UX built for speed and cravings.',
    'brief'=>'Cravio needed a complete UI/UX design for their food delivery app — restaurant discovery, search and filtering, cart and checkout, live order tracking, and a promotional offers system — targeting urban Nigerian food lovers.',
    'problem'=>'The food delivery market in Nigeria was dominated by apps with poor UI that made ordering feel laborious. Cravio wanted a design that felt as fast and exciting as the food itself — reducing time from craving to order placed.',
    'process'=>'Competitive analysis of 8 food delivery apps globally identified the key friction points: slow restaurant discovery, cluttered menus, and confusing checkout flows. Every screen was designed to reduce the number of taps required.',
    'solution'=>'A high-energy food delivery app with a bold orange visual identity, personalised home feed, cuisine category filtering, smart restaurant cards with live delivery times, a one-page checkout, and real-time order tracking.',
    'output'=>'iOS and Android Figma design files, full design system, interactive prototype, and developer handoff documentation.',
  ],
  [
    'id'=>17,'cat'=>'uiux','cat_label'=>'UI/UX Design',
    'bg'=>'linear-gradient(145deg,#0A0612 0%,#7C3AED 100%)',
    'image'=>'images/ui5.png',
    'url'=>'',
    'title'=>'Skillrift — E-Learning Platform',
    'tagline'=>'AI-powered e-learning platform UI/UX with 2,400+ courses and smart learning paths.',
    'brief'=>'Skillrift needed a complete UI/UX design for their e-learning platform — course discovery, AI-powered learning path recommendations, progress tracking, a community feed, mentor matching, and a learner dashboard.',
    'problem'=>'Online learners in Africa consistently reported that existing e-learning platforms felt foreign and unmotivating. Skillrift needed a design that combined world-class course quality with an experience that felt local, engaging, and accountable.',
    'process'=>'We ran focus groups with 30 African learners and identified three core retention drivers: visible progress, peer accountability, and personalised recommendations. The dashboard was designed around all three simultaneously.',
    'solution'=>'A dark-mode learning platform with a personalised dashboard, AI course recommendations, visual progress tracking, a daily streak system, community leaderboards, and a clean course player — all built on a purple and cyan visual system.',
    'output'=>'Desktop and mobile Figma design files, full design system, interactive prototype, AI recommendation UX flows, and developer handoff documentation.',
  ],
  [
    'id'=>18,'cat'=>'uiux','cat_label'=>'UI/UX Design',
    'bg'=>'linear-gradient(145deg,#080808 0%,#E63214 100%)',
    'image'=>'images/ui6.png',
    'url'=>'',
    'title'=>'Apex — Fitness & Training App',
    'tagline'=>'High-performance fitness app UI/UX for serious athletes and everyday trainers.',
    'brief'=>'Apex needed a complete UI/UX design for their fitness app — personalised workout programs, daily metrics tracking, exercise library, nutrition logging, progress analytics, and a coach connection feature — targeting performance-focused users.',
    'problem'=>'Fitness apps either catered to casual users with oversimplified tracking, or to elite athletes with overwhelming complexity. Apex needed a design that felt powerfully capable without being intimidating.',
    'process'=>'User interviews with 20 gym-goers across different fitness levels revealed that motivation through visible data was the number one retention factor. The dashboard was designed to make every workout feel like a meaningful achievement.',
    'solution'=>'A bold dark fitness app with an aggressive red accent system, a daily performance dashboard showing calories burned, steps, and active time, a workout card system, muscle group progress bars, and a streak-based motivation system.',
    'output'=>'iOS and Android Figma design files, full design system, exercise animation specs, interactive prototype, and developer handoff documentation.',
  ],
  [
    'id'=>19,'cat'=>'uiux','cat_label'=>'UI/UX Design',
    'bg'=>'linear-gradient(145deg,#F8F4EF 0%,#1C1612 100%)',
    'image'=>'images/ui7.png',
    'url'=>'',
    'title'=>'Aurel — Luxury Fashion House',
    'tagline'=>'Editorial three-column UI/UX design for a Nigerian luxury couture brand.',
    'brief'=>'Aurel needed a complete UI/UX design for their luxury fashion e-commerce platform — collection presentation, bespoke product pages, couture sizing and customisation flows, lookbook integration, and a high-end checkout experience.',
    'problem'=>'Nigerian luxury fashion brands lacked a digital retail experience that matched the quality of their physical products. Aurel needed a platform that communicated couture-level prestige and justified premium pricing.',
    'process'=>'We benchmarked the digital experiences of the world\'s top luxury fashion houses — Bottega Veneta, The Row, Jil Sander — and identified the visual language of restraint, whitespace, and editorial typography as the universal markers of luxury.',
    'solution'=>'A three-column editorial layout that simultaneously presents the brand story, the hero product, and the brand\'s value proposition. An ivory and charcoal colour system, Garamond serif typography, and deliberate negative space communicate understated luxury throughout.',
    'output'=>'Full desktop and mobile Figma design files, design system, lookbook template, checkout flow prototype, and developer handoff documentation.',
  ],
  [
    'id'=>20,'cat'=>'uiux','cat_label'=>'UI/UX Design',
    'bg'=>'linear-gradient(145deg,#070D1A 0%,#38BDF8 100%)',
    'image'=>'images/ui8.png',
    'url'=>'',
    'title'=>'Trackr — Logistics Dashboard',
    'tagline'=>'Real-time logistics operations dashboard for a large-scale fleet management company.',
    'brief'=>'Trackr needed a complete UI/UX design for their logistics operations dashboard — live fleet tracking, shipment status management, KPI monitoring, driver and vehicle management, route optimisation, and an alerts system — for a fleet of 200+ vehicles.',
    'problem'=>'Fleet managers were making critical operational decisions using spreadsheets and phone calls. The information they needed was scattered across multiple systems, making real-time decision-making slow and error-prone.',
    'process'=>'We conducted contextual inquiry sessions with four fleet managers over three days, observing their actual workflows and identifying the 12 data points they checked most urgently in a crisis. The dashboard was designed around those 12 points.',
    'solution'=>'A dense but highly usable dark operations dashboard with a live fleet map, real-time shipment status table, four KPI cards with trend indicators, a sidebar navigation system, and colour-coded status badges — all using a blue and dark navy technical visual language.',
    'output'=>'Full desktop Figma design files, design system, component library, interactive prototype, and developer handoff documentation.',
  ],

  // ── MOTION DESIGN (21–32) ─────────────────────────────────────────────────
  [
    'id'=>21,'cat'=>'motion','cat_label'=>'Motion Design',
    'bg'=>'linear-gradient(145deg,#1a0a00 0%,#7A3000 50%,#F5B301 100%)',
    'image'=>'images/vid1.jpeg',
    'url'=>'https://youtu.be/F6aZyJZBtsg',
    'title'=>'You Owe It To Yourself In 2025',
    'tagline'=>'3D animated motivational video inspired by Eric Thomas for OMG Motivation YouTube channel.',
  ],
  [
    'id'=>22,'cat'=>'motion','cat_label'=>'Motion Design',
    'bg'=>'linear-gradient(145deg,#1a0800 0%,#8B3000 50%,#FF6B00 100%)',
    'image'=>'images/vid2.jpeg',
    'url'=>'https://youtu.be/0L9c9iJUlfg',
    'title'=>'The Lost Wallet — A Tale Of Honesty',
    'tagline'=>'Captivating live-action story video for OMG Motivation YouTube channel.',
  ],
  [
    'id'=>23,'cat'=>'motion','cat_label'=>'Motion Design',
    'bg'=>'linear-gradient(145deg,#1a0a05 0%,#4a1500 50%,#c85000 100%)',
    'image'=>'images/vid3.jpeg',
    'url'=>'https://youtu.be/L3D_2WHDbmM',
    'title'=>'Look Before You Leap',
    'tagline'=>'3D cartoon character animation and scene production for OMG Motivation YouTube channel.',
  ],
  [
    'id'=>24,'cat'=>'motion','cat_label'=>'Motion Design',
    'bg'=>'linear-gradient(145deg,#1a0a00 0%,#7A3000 50%,#F5B301 100%)',
    'image'=>'images/vid4.jpeg',
    'url'=>'https://youtu.be/z6yV-JNUZqc',
    'title'=>'You Are Unstoppable',
    'tagline'=>'3D animated motivational video for OMG Motivation YouTube channel.',
  ],
  [
    'id'=>25,'cat'=>'motion','cat_label'=>'Motion Design',
    'bg'=>'linear-gradient(145deg,#0a0030 0%,#2d0080 50%,#ff80ff 100%)',
    'image'=>'images/vid5.jpeg',
    'url'=>'https://youtube.com/shorts/k9EqxDoBKk4',
    'title'=>'OMG Animation Of America\'s Got Talent',
    'tagline'=>'Cinematic transition video production and visual effects for OMG Motivation YouTube channel.',
  ],
  [
    'id'=>26,'cat'=>'motion','cat_label'=>'Motion Design',
    'bg'=>'linear-gradient(145deg,#0d4040 0%,#16a34a 50%,#c87800 100%)',
    'image'=>'images/vid6.jpeg',
    'url'=>'https://youtu.be/86cGOmtirMU',
    'title'=>'The Lost Wallet — Part Two',
    'tagline'=>'Continuation of the viral story series for OMG Motivation YouTube channel.',
  ],
  [
    'id'=>27,'cat'=>'motion','cat_label'=>'Motion Design',
    'bg'=>'linear-gradient(145deg,#1a0800 0%,#7A3000 50%,#FFD700 100%)',
    'image'=>'images/vid7.jpeg',
    'url'=>'https://youtu.be/OLI8yTrkZvs',
    'title'=>'The Boy With The Golden Voice',
    'tagline'=>'Emotional animated story video for OMG Motivation YouTube channel.',
  ],
  [
    'id'=>28,'cat'=>'motion','cat_label'=>'Motion Design',
    'bg'=>'linear-gradient(145deg,#0a0a1a 0%,#001050 50%,#cc0000 100%)',
    'image'=>'images/vid8.jpeg',
    'url'=>'https://youtu.be/b41EqpMLIsc',
    'title'=>'Release VeryDarkMan Now!',
    'tagline'=>'Powerfully animated video of Donald Trump asking for the release of VeryDarkMan.',
  ],
  [
    'id'=>29,'cat'=>'motion','cat_label'=>'Motion Design',
    'bg'=>'linear-gradient(145deg,#1a0505 0%,#7A0D0D 50%,#FFD700 100%)',
    'image'=>'images/vid9.jpeg',
    'url'=>'https://youtu.be/MyQNG8mX0QE',
    'title'=>'Omigie Graphics — Brand Animation',
    'tagline'=>'2D brand animation and character design for Omigie Graphics.',
  ],
  [
    'id'=>30,'cat'=>'motion','cat_label'=>'Motion Design',
    'bg'=>'linear-gradient(145deg,#001a10 0%,#16a34a 50%,#c8a050 100%)',
    'image'=>'images/vid10.jpeg',
    'url'=>'https://youtube.com/shorts/b81xqiV21eM',
    'title'=>'Never Give Up — Animated Short',
    'tagline'=>'2D animated motivational video for OMG Motivation YouTube channel.',
  ],
  [
    'id'=>31,'cat'=>'motion','cat_label'=>'Motion Design',
    'bg'=>'linear-gradient(145deg,#1a0030 0%,#cc0050 50%,#0066cc 100%)',
    'image'=>'images/vid11.jpeg',
    'url'=>'https://youtu.be/juKs8TLy0Co',
    'title'=>'OMG TV — Live Studio Production',
    'tagline'=>'Complete animated live action video production and studio direction for OMG TV YouTube channel.',
  ],
  [
    'id'=>32,'cat'=>'motion','cat_label'=>'Motion Design',
    'bg'=>'linear-gradient(145deg,#0a1a0a 0%,#16a34a 50%,#c8a050 100%)',
    'image'=>'images/vid12.jpeg',
    'url'=>'https://youtu.be/VAjunYB20Lg',
    'title'=>'This TOO shall Pass',
    'tagline'=>'2D animated motivational cartoon for OMG Motivation YouTube channel.',
  ],
];